#name: Build and Test
#
#on:
#  push:
#    branches-ignore:
#      - master  # Exclude main branch
#
#jobs:
#  build-and-test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '9.x'  # Replace with your .NET version
#
#      - name: Restore dependencies
#        run: dotnet restore --force-evaluate
#
#      - name: Build
#        run: dotnet build --no-restore
#
#      - name: Run tests
#        run: dotnet test --no-build