name: Build and Test

on:
  push:
    branches-ignore:
      - master  # Exclude main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.101' # Specify exact .NET version

      - name: Clear NuGet Cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore --use-lock-file

      - name: Clean Solution
        run: dotnet clean

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build